version: '2'

services:
  monerod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: v0.18.3.1
        # BRANCH: master
        DEBIAN_VERSION: "stable-slim"
    command: --testnet --data-dir /monero --ban-list /data/block_tor.txt
    volumes:
      # /monero in container should eventually contain the contents of the folder .bitmonero
      - <path/to/and/including/.bitmonero>:/monero
      - ${PWD}/block_tor.txt:/data/block_tor.txt
    ports:
      - "28080:28080"
      - "28081:28081"
    stdin_open: true
    tty: true
    read_only: true
    init: true
    security_opt:
      - no-new-privileges: true
    tmpfs:
      - /run/monero
      - /var/lib/tor
    environment:
      - USER_ID=1000
      - P2P_BIND_IP=0.0.0.0
      - P2P_BIND_PORT=28080
      - LOG_LEVEL=0
      - RPC_USER=""
      - RPC_PASSWD=""
      - RPC_BIND_IP=0.0.0.0
      - RPC_BIND_PORT=28081
      - USE_TORSOCKS=NO
      - USE_TOR=NO
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
