#!/bin/bash

# post
docker tag $IMAGE_NAME $DOCKER_REPO:$MOST_RECENT_TAG_NAME
docker push $DOCKER_REPO:$MOST_RECENT_TAG_NAME

if [ "$RELEASE_BRANCH" = "$SOURCE_BRANCH" ]; then
  curl -X POST \
       -F token=$MONERO_TESTNET_TOKEN \
       -F ref=$SOURCE_BRANCH \
       $MONERO_TESTNET_URL
fi

